/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import controllers.ControllerFornecedor;
import br.com.adapters.AdpterFornecedorJTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import model.Fornecedor;

/**
 *
 * @author Vinicius Ricardo Zoqueti
 */
public class JanelaFornecedores extends javax.swing.JFrame {

    private ControllerFornecedor fornecedorController;
    private AdpterFornecedorJTable adapterFornecedorJTable;
    private long idSelecionado = 0;
    private boolean editar = false;

    /**
     * Creates new form JanelaFornecedores
     */
    public JanelaFornecedores() throws InstantiationException, IllegalAccessException {
        this.fornecedorController = new ControllerFornecedor();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);;
        load();

    }

    public void filtrarTabela(String valueFilter) {

        TableRowSorter sorter = new TableRowSorter(adapterFornecedorJTable);
        jtbFornecedores.setRowSorter(sorter);

        if (valueFilter.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {

                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + valueFilter));

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar o valor!!!", "AVISO - Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private void load() {

        List<Fornecedor> fornecedores = null;
        try {

            adapterFornecedorJTable = fornecedorController.AllTable();
            jtbFornecedores.setModel(adapterFornecedorJTable);
        } catch (SQLException ex) {
            Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void tableaValue() {
        int row = jtbFornecedores.getSelectedRow();
        Fornecedor fornecedor = adapterFornecedorJTable.getValue(row);
        idSelecionado = fornecedor.getId();
        jbtnEditar.setEnabled(true);
        jbtnExcluir.setEnabled(true);
        jtxtRazao.setText(fornecedor.getRazao());
        jtxtFantasia.setText("Faltando");
        jtxtCnpjCpf.setText(fornecedor.getCpf_cnpj());
        jtxtInscricao.setText(fornecedor.getRg_insc());
        jtxtTelefone.setText(fornecedor.getTelefone());
    }

    private void salvar(boolean editar) {

        String razao = jtxtRazao.getText();
        String fantasia = jtxtFantasia.getText();
        String cpfCnpj = jtxtCnpjCpf.getText();
        String incricao = jtxtInscricao.getText();
        String telefone = jtxtTelefone.getText();
        Fornecedor fornecedor = new Fornecedor((int) idSelecionado, razao, cpfCnpj, incricao, telefone, fantasia);

        boolean result = true;

        if (editar) {

            try {

                fornecedorController.Editar(fornecedor);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
                result = false;
            }
        } else {

            try {
                fornecedorController.Adicionar(fornecedor);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
                result = false;
            }
        }

        if (result) {
            idSelecionado = 0;
            jbtnNovo.setEnabled(true);
            jbtnEditar.setEnabled(false);
            jbtnExcluir.setEnabled(false);
            jbtnSalvar.setEnabled(false);
            jbtnCancelar.setEnabled(false);
            jtbFornecedores.setEnabled(true);

            jtxtRazao.setEnabled(false);
            jtxtFantasia.setEnabled(false);
            jtxtCnpjCpf.setEnabled(false);
            jtxtInscricao.setEnabled(false);
            jtxtTelefone.setEnabled(false);

            jtxtRazao.setText("");
            jtxtFantasia.setText("");
            jtxtCnpjCpf.setText("");
            jtxtInscricao.setText("");
            jtxtTelefone.setText("");

            load();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jtxtBuscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtFantasia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtxtCnpjCpf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbFornecedores = new javax.swing.JTable();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jtxtInscricao = new javax.swing.JTextField();
        jtxtTelefone = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxtRazao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnNovo = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 153, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("REALIZAR FORNECEDOR");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconsContabilidade_80px.png"))); // NOI18N

        jtxtBuscar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel15.setText("Razão:");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel18.setText("Fantasia:");

        jtxtFantasia.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtxtFantasia.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel19.setText("CPF/CNPJ:");

        jtxtCnpjCpf.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtxtCnpjCpf.setEnabled(false);

        jtbFornecedores.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jtbFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbFornecedoresMouseClicked(evt);
            }
        });
        jtbFornecedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbFornecedoresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbFornecedoresKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbFornecedores);

        jbtnSalvar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnSalvar.setText("SALVAR");
        jbtnSalvar.setEnabled(false);
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnEditar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnEditar.setText("EDITAR");
        jbtnEditar.setEnabled(false);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jbtnExcluir.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnExcluir.setText("EXCLUIR");
        jbtnExcluir.setEnabled(false);
        jbtnExcluir.setName(""); // NOI18N
        jbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel20.setText("Inscrição:");

        jtxtInscricao.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtxtInscricao.setEnabled(false);

        jtxtTelefone.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtxtTelefone.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel21.setText("Telefone:");

        jtxtRazao.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jtxtRazao.setEnabled(false);

        jLabel3.setText("Buscar:");

        jbtnNovo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnNovo.setText("NOVO");
        jbtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoActionPerformed(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbtnCancelar.setText("CANCELAR");
        jbtnCancelar.setEnabled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jtxtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jbtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnCancelar))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jtxtCnpjCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jtxtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jtxtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(58, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jbtnNovo))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jtxtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnSalvar)
                        .addComponent(jbtnEditar)
                        .addComponent(jbtnExcluir)
                        .addComponent(jbtnCancelar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtxtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtxtCnpjCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jtxtInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("FORNECEDOR", jPanel3);

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoActionPerformed
        idSelecionado = 0;
        this.editar = false;
        jbtnNovo.setEnabled(false);
        jbtnSalvar.setEnabled(true);
        jbtnCancelar.setEnabled(true);
        jtbFornecedores.setEnabled(false);

        jtbFornecedores.setEnabled(false);

        jtxtRazao.setEnabled(true);
        jtxtFantasia.setEnabled(true);
        jtxtCnpjCpf.setEnabled(true);
        jtxtInscricao.setEnabled(true);
        jtxtTelefone.setEnabled(true);

        jtxtRazao.setText("");
        jtxtFantasia.setText("");
        jtxtCnpjCpf.setText("");
        jtxtInscricao.setText("");
        jtxtTelefone.setText("");


    }//GEN-LAST:event_jbtnNovoActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.editar = false;
        jbtnNovo.setEnabled(true);
        jbtnEditar.setEnabled(false);
        jbtnExcluir.setEnabled(false);
        jbtnSalvar.setEnabled(false);
        jbtnCancelar.setEnabled(false);

        jtbFornecedores.setEnabled(true);

        jtxtRazao.setEnabled(false);
        jtxtFantasia.setEnabled(false);
        jtxtCnpjCpf.setEnabled(false);
        jtxtInscricao.setEnabled(false);
        jtxtTelefone.setEnabled(false);


    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja deletar?");

        if (option != 0) {
            return;
        }

        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setId((int) idSelecionado);
        boolean result = true;

        try {
            fornecedorController.Excluir(fornecedor);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            result = false;
        }

        if (result) {
            this.idSelecionado = 0;
            jbtnExcluir.setEnabled(false);

            jtbFornecedores.setEnabled(true);

            jtxtRazao.setEnabled(false);
            jtxtFantasia.setEnabled(false);
            jtxtCnpjCpf.setEnabled(false);
            jtxtInscricao.setEnabled(false);
            jtxtTelefone.setEnabled(false);

            jtxtRazao.setText("");
            jtxtFantasia.setText("");
            jtxtCnpjCpf.setText("");
            jtxtInscricao.setText("");
            jtxtTelefone.setText("");

            load();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar");
        }
    }//GEN-LAST:event_jbtnExcluirActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        salvar(this.editar);
        this.editar = false;
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        this.editar = true;
        jbtnNovo.setEnabled(false);
        jbtnEditar.setEnabled(false);
        jbtnExcluir.setEnabled(false);
        jbtnSalvar.setEnabled(true);
        jbtnCancelar.setEnabled(true);

        jtbFornecedores.setEnabled(true);

        jtxtRazao.setEnabled(true);
        jtxtFantasia.setEnabled(true);
        jtxtCnpjCpf.setEnabled(true);
        jtxtInscricao.setEnabled(true);
        jtxtTelefone.setEnabled(true);

    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtbFornecedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbFornecedoresKeyPressed
       
    }//GEN-LAST:event_jtbFornecedoresKeyPressed

    private void jtbFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbFornecedoresMouseClicked
        tableaValue();
    }//GEN-LAST:event_jtbFornecedoresMouseClicked

    private void jtxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyReleased
        filtrarTabela(jtxtBuscar.getText());
    }//GEN-LAST:event_jtxtBuscarKeyReleased

    private void jtbFornecedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbFornecedoresKeyReleased
       tableaValue();
    }//GEN-LAST:event_jtbFornecedoresKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaFornecedores().setVisible(true);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JanelaFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JanelaFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JTable jtbFornecedores;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtCnpjCpf;
    private javax.swing.JTextField jtxtFantasia;
    private javax.swing.JTextField jtxtInscricao;
    private javax.swing.JTextField jtxtRazao;
    private javax.swing.JTextField jtxtTelefone;
    // End of variables declaration//GEN-END:variables
}
